# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:20
from __future__ import unicode_literals

import cap.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=255, unique=True)),
                ('orig_xml', cap.models.XMLField()),
            ],
        ),
        migrations.CreateModel(
            name='DataMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_migration_timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'applied'), ('pending', 'pending'), ('error', 'error')], max_length=10)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=255)),
                ('initiator', models.CharField(max_length=255)),
                ('alto_xml_changed', django.contrib.postgres.fields.jsonb.JSONField()),
                ('volume_xml_changed', django.contrib.postgres.fields.jsonb.JSONField()),
                ('case_xml_changed', django.contrib.postgres.fields.jsonb.JSONField()),
                ('alto_xml_rollback', django.contrib.postgres.fields.jsonb.JSONField()),
                ('volume_xml_rollback', django.contrib.postgres.fields.jsonb.JSONField()),
                ('case_xml_rollback', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=255, unique=True)),
                ('orig_xml', cap.models.XMLField()),
                ('cases', models.ManyToManyField(related_name='pages', to='cap.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=255, unique=True)),
                ('orig_xml', cap.models.XMLField()),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap.Volume'),
        ),
        migrations.AddField(
            model_name='case',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap.Volume'),
        ),
    ]
