# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0003_auto_20170705_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=64, null=True)),
                ('first_page', models.IntegerField(blank=True, null=True)),
                ('last_page', models.IntegerField(blank=True, null=True)),
                ('docket_number', models.CharField(blank=True, max_length=255)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_date_original', models.CharField(blank=True, max_length=100)),
                ('name', models.TextField(blank=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('official', 'official'), ('parallel', 'parallel')], max_length=100)),
                ('cite', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_abbreviation', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='casexml',
            old_name='barcode',
            new_name='case_id',
        ),
        migrations.RemoveField(
            model_name='reporter',
            name='jurisdiction',
        ),
        migrations.AlterField(
            model_name='trackingtoollog',
            name='exception',
            field=models.BooleanField(help_text="Nothing to do with software exceptions - more like a UPS delivery 'exception'"),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='hollis_number',
            field=models.CharField(help_text='Identifier in the Harvard cataloging system, HOLLIS', max_length=9),
        ),
        migrations.AddField(
            model_name='court',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_jurisdiction', to='capdb.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='citation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casemetadata_citation', to='capdb.Citation'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_court', to='capdb.Court'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_jurisdiction', to='capdb.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_reporter', to='capdb.Reporter'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_volume', to='capdb.VolumeMetadata'),
        ),
        migrations.AddField(
            model_name='reporter',
            name='jurisdictions',
            field=models.ManyToManyField(to='capdb.Jurisdiction'),
        ),
    ]
