# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0004_auto_20170706_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('official', 'official'), ('parallel', 'parallel')], max_length=10)),
                ('cite', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='jurisdiction_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='citation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casemetadata_citation', to='cap.Citation'),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_volume', to='cap.VolumeMetadata'),
        ),
        migrations.AlterField(
            model_name='trackingtoollog',
            name='exception',
            field=models.BooleanField(help_text="Nothing to do with software exceptions - more like a UPS delivery 'exception'"),
        ),
    ]
