# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0005_casemetadata_duplicative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='type',
            field=models.CharField(choices=[('official', 'official'), ('parallel', 'parallel'), ('duplicative', 'duplicative')], max_length=100),
        ),
    ]
