# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0006_auto_20170822_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemetadata',
            name='citation',
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='citations',
            field=models.ManyToManyField(related_name='casemetadata_citation', to='capdb.Citation'),
        ),
        migrations.AddField(
            model_name='citation',
            name='duplicative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citation',
            name='type',
            field=models.CharField(choices=[('official', 'official'), ('parallel', 'parallel')], max_length=100),
        ),
    ]
