# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0007_auto_20170905_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
