# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-20 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0007_auto_20170905_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='casexml',
            name='s3_key',
            field=models.CharField(blank=True, help_text='s3 path', max_length=1024),
        ),
        migrations.AddField(
            model_name='pagexml',
            name='s3_key',
            field=models.CharField(blank=True, help_text='s3 path', max_length=1024),
        ),
        migrations.AddField(
            model_name='volumexml',
            name='s3_key',
            field=models.CharField(blank=True, help_text='s3 path', max_length=1024),
        ),
    ]
