# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-27 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0008_auto_20170920_2139'),
        ('capdb', '0009_casemetadata_fill_slug'),
    ]

    operations = [
    ]
