# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0014_auto_20171211_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casexml',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_xml', to='capdb.CaseMetadata'),
        ),
        migrations.AlterField(
            model_name='casexml',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='case_xmls', to='capdb.VolumeXML'),
        ),
        migrations.AlterField(
            model_name='pagexml',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_xmls', to='capdb.VolumeXML'),
        ),
        migrations.AlterField(
            model_name='trackingtoollog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_tool_logs', to='capdb.TrackingToolUser'),
        ),
        migrations.AlterField(
            model_name='trackingtoollog',
            name='pstep',
            field=models.ForeignKey(blank=True, help_text='A significant event in production', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_tool_logs', to='capdb.ProcessStep'),
        ),
        migrations.AlterField(
            model_name='trackingtoollog',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_tool_logs', to='capdb.VolumeMetadata'),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capdb.TrackingToolUser'),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capdb.Reporter'),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capdb.BookRequest'),
        ),
        migrations.AlterField(
            model_name='volumexml',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volume_xml', to='capdb.VolumeMetadata'),
        ),
    ]
