# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0015_auto_20171212_1749'),
        ('capdb', '0013_auto_20171213_1548'),
    ]

    operations = [
    ]
