# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0016_merge_20171214_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='cite',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
