# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0019_auto_20171218_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetadata',
            name='name_abbreviation',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
