# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0020_auto_20171218_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='casexml',
            name='md5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagexml',
            name='md5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volumexml',
            name='md5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
