# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0021_auto_20171219_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='attorneys',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='judges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='opinion_dissent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='opinion_majority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='parties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
