# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-12 19:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0022_auto_20180118_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumemetadata',
            name='ingest_errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='ingest_status',
            field=models.CharField(choices=[('to_ingest', 'to_ingest'), ('ingested', 'ingested'), ('error', 'error'), ('skip', 'skip')], default='to_ingest', max_length=10),
        ),
    ]
