# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-15 16:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0023_auto_20180212_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetadata',
            name='attorneys',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='judges',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='opinions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='parties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
