# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0024_auto_20180215_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetadata',
            name='docket_number',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
