# Generated by Django 2.0.2 on 2018-03-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0025_auto_20180220_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemetadata',
            options={'ordering': ['decision_date']},
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='slug',
        ),
        migrations.AddField(
            model_name='citation',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations', to='capdb.CaseMetadata'),
        ),
        migrations.AddField(
            model_name='citation',
            name='normalized_cite',
            field=models.SlugField(max_length=10000, null=True),
        ),
    ]
