# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify
from scripts.helpers import chunked_iterator


def create_normalized_cite(apps, schema_editor):
    Citation = apps.get_model("capdb", "Citation")
    cites = Citation.objects.all()

    for cite in chunked_iterator(cites):
        cite.normalized_cite = slugify(cite.cite)
        cite.save()


def delete_normalized_cite(apps, schema_editor):
    Citation = apps.get_model("capdb", "Citation")
    cites = Citation.objects.all()

    for cite in chunked_iterator(cites):
        cite.normalized_cite = ''
        cite.save()


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0025_auto_20180220_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemetadata',
            options={'ordering': ['decision_date']},
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='citation',
            name='slug',
        ),
        migrations.AddField(
            model_name='citation',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='capdb.CaseMetadata'),
        ),
        migrations.AddField(
            model_name='citation',
            name='normalized_cite',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.RunPython(create_normalized_cite, delete_normalized_cite),
    ]
