# Generated by Django 2.0.2 on 2018-03-14 21:00

import capdb.models
import capdb.versioning
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0026_auto_20180307_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCaseXML',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('orig_xml', capdb.models.XMLField()),
                ('md5', models.CharField(blank=True, max_length=255, null=True)),
                ('case_id', models.CharField(db_index=True, max_length=255)),
                ('s3_key', models.CharField(blank=True, help_text='s3 path', max_length=1024)),
                ('sys_period', capdb.versioning.DefaultDateTimeRangeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.CaseMetadata')),
            ],
            options={
                'get_latest_by': 'history_date',
                'db_table': 'capdb_casexml_history',
                'ordering': ('-sys_period', '-history_id'),
                'verbose_name': 'historical case xml',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPageXML',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('orig_xml', capdb.models.XMLField()),
                ('md5', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(db_index=True, max_length=255)),
                ('s3_key', models.CharField(blank=True, help_text='s3 path', max_length=1024)),
                ('sys_period', capdb.versioning.DefaultDateTimeRangeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'get_latest_by': 'history_date',
                'db_table': 'capdb_pagexml_history',
                'ordering': ('-sys_period', '-history_id'),
                'verbose_name': 'historical page xml',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVolumeXML',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('orig_xml', capdb.models.XMLField()),
                ('md5', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_key', models.CharField(blank=True, help_text='s3 path', max_length=1024)),
                ('sys_period', capdb.versioning.DefaultDateTimeRangeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('metadata', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.VolumeMetadata')),
            ],
            options={
                'get_latest_by': 'history_date',
                'db_table': 'capdb_volumexml_history',
                'ordering': ('-sys_period', '-history_id'),
                'verbose_name': 'historical volume xml',
            },
        ),
        migrations.AddField(
            model_name='casexml',
            name='sys_period',
            field=capdb.versioning.DefaultDateTimeRangeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagexml',
            name='sys_period',
            field=capdb.versioning.DefaultDateTimeRangeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volumexml',
            name='sys_period',
            field=capdb.versioning.DefaultDateTimeRangeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpagexml',
            name='volume',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.VolumeXML'),
        ),
        migrations.AddField(
            model_name='historicalcasexml',
            name='volume',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.VolumeXML'),
        ),
    ]
