# Generated by Django 2.0.2 on 2018-02-28 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0026_auto_20180227_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='citation', to='capdb.CaseMetadata'),
        ),
    ]
