# Generated by Django 2.0.2 on 2018-03-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0027_auto_20180314_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casexml',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='historicalcasexml',
            name='case_id',
        ),
    ]
