# Generated by Django 2.0.2 on 2018-03-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0030_auto_20180321_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagexml',
            options={'ordering': ['barcode']},
        ),
    ]
