# Generated by Django 2.0.2 on 2018-04-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0031_auto_20180329_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='name_long',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='full_name',
            field=models.CharField(db_index=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='name_abbreviation',
            field=models.CharField(blank=True, db_index=True, max_length=1024),
        ),
        # migrations.RunSQL(
        #     sql='CREATE INDEX idx_casemetadata_name_abbr_upper ON capdb_casemetadata (UPPER(name_abbreviation) varchar_pattern_ops);',
        #     reverse_sql='DROP INDEX idx_casemetadata_name_abbr_upper;'
        # ),
        # migrations.RunSQL(
        #     sql='CREATE INDEX idx_court_name_upper ON capdb_court (UPPER(name) varchar_pattern_ops);',
        #     reverse_sql='DROP INDEX idx_court_name_upper;'
        # ),
        # migrations.RunSQL(
        #     sql='CREATE INDEX idx_reporter_name_upper ON capdb_reporter (UPPER(full_name) varchar_pattern_ops);',
        #     reverse_sql='DROP INDEX idx_reporter_name_upper;'
        # ),
    ]
