# Generated by Django 2.0.2 on 2018-04-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0035_slowquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemetadata',
            options={},
        ),
    ]
