# Generated by Django 2.0.2 on 2018-04-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0036_auto_20180419_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_publication_city',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_reporter_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_reporter_short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='xml_volume_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
