# Generated by Django 2.0.2 on 2018-04-27 20:49

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0036_auto_20180419_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='jurisdiction_slug',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='capdb.Jurisdiction',
                related_name='case_metadatas',
                to_field='slug'),
        ),
    ]
