# Generated by Django 2.0.2 on 2018-04-27 21:21

from django.db import migrations
from scripts.helpers import chunked_iterator


def copy_to_new_jurisdiction(apps, schema_editor):
    CaseMetadata = apps.get_model("capdb", "CaseMetadata")
    cases = CaseMetadata.objects.all().order_by('id')
    for case in chunked_iterator(cases):
        case.jurisdiction_slug = case.jurisdiction
        case.save()
    print('done.')


def remove_new_jurisdiction(apps, schema_editor):
    CaseMetadata = apps.get_model("capdb", "CaseMetadata")
    cases = CaseMetadata.objects.all().order_by('id')
    for case in chunked_iterator(cases):
        case.jurisdiction = case.jurisdiction_slug
        case.save()
    print('done.')


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0037_auto_20180427_2049'),
    ]

    operations = [
        # copy all jurisdictions to the new jurisdiction
        migrations.RunPython(copy_to_new_jurisdiction, remove_new_jurisdiction),
    ]
