# Generated by Django 2.0.2 on 2018-05-21 15:11

from django.db import migrations

from scripts.set_up_postgres import initialize_denormalization_fields


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0038_auto_20180510_1429'),
    ]

    operations = [
        # populate denormalized fields created above
        migrations.RunPython(initialize_denormalization_fields, migrations.RunPython.noop),
    ]
