# Generated by Django 2.0.2 on 2018-04-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0038_auto_20180427_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemetadata',
            name='jurisdiction',
        ),
        migrations.RenameField(
            model_name='casemetadata',
            old_name='jurisdiction_slug',
            new_name='jurisdiction',
        ),

    ]
