# Generated by Django 2.0.2 on 2018-06-14 15:24

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0041_auto_20180525_1952'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='casemetadata',
            name='capdb_casem_decisio_84c016_idx',
        ),
        migrations.RemoveIndex(
            model_name='casemetadata',
            name='capdb_casem_jurisdi_429073_idx',
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=partial_index.PartialIndex(fields=['decision_date', 'id'], name='capdb_casem_decisio_1d682b_partial', unique=True, where='jurisdiction_id IS NOT NULL AND court_id IS NOT NULL AND NOT duplicative', where_postgresql='', where_sqlite=''),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=partial_index.PartialIndex(fields=['jurisdiction_slug', 'decision_date', 'id'], name='capdb_casem_jurisdi_7edf20_partial', unique=True, where='jurisdiction_id IS NOT NULL AND court_id IS NOT NULL AND NOT duplicative', where_postgresql='', where_sqlite=''),
        ),
    ]
