# Generated by Django 2.0.2 on 2018-06-14 16:49

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0042_auto_20180614_1524'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='casemetadata',
            index=partial_index.PartialIndex(fields=['court', 'decision_date', 'id'], name='capdb_casem_court_i_42eeb9_partial', unique=True, where='jurisdiction_id IS NOT NULL AND court_id IS NOT NULL AND NOT duplicative', where_postgresql='', where_sqlite=''),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=partial_index.PartialIndex(fields=['reporter', 'decision_date', 'id'], name='capdb_casem_reporte_3f581c_partial', unique=True, where='jurisdiction_id IS NOT NULL AND court_id IS NOT NULL AND NOT duplicative', where_postgresql='', where_sqlite=''),
        ),
    ]
