# Generated by Django 2.0.2 on 2018-07-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0044_auto_20180614_1750'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE INDEX idx_casemetadata_docket_number_upper ON capdb_casemetadata USING GIN (UPPER(docket_number) gin_trgm_ops);',
            reverse_sql='DROP INDEX idx_casemetadata_docket_number_upper;',
        ),
    ]
