# Generated by Django 2.0.2 on 2018-07-10 18:20

from django.db import migrations, models
import partial_index
from scripts.set_up_postgres import initialize_denormalization_fields


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0044_auto_20180614_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='court_name_abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='court_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=partial_index.PartialIndex(fields=['court_slug', 'decision_date', 'id'],
                                             name='capdb_casem_court_s_34d559_partial',
                                             unique=True,
                                             where='jurisdiction_id IS NOT NULL AND court_id IS NOT NULL AND NOT duplicative',
                                             where_postgresql='', where_sqlite=''),
        ),
        migrations.RunPython(initialize_denormalization_fields, migrations.RunPython.noop),
    ]
