# Generated by Django 2.0.2 on 2018-07-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0045_docketnumber_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='court_name_abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='court_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
