# Generated by Django 2.0.8 on 2018-08-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0046_court_denormalization'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE capdb_citation SET normalized_cite = regexp_replace(normalized_cite, '[^0-9a-z]', '', 'g');",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
