# Generated by Django 2.0.8 on 2018-08-27 20:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0047_auto_20180814_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('body_format', models.CharField(choices=[('xml', 'xml'), ('text', 'text')], max_length=10)),
                ('export_date', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('filter_type', models.CharField(choices=[('jurisdiction', 'jurisdiction'), ('reporter', 'reporter')], max_length=20)),
                ('filter_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
