# Generated by Django 2.0.8 on 2018-08-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0047_auto_20180814_1955'),
        ('capdb', '0047_auto_20180813_2042'),
    ]

    operations = [
    ]
