# Generated by Django 2.0.8 on 2018-08-20 18:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0048_merge_20180820_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetadata',
            name='tsvector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tsvector'], name='capdb_casem_tsvecto_a0d06d_gin'),
        ),
    ]
