# Generated by Django 2.0.8 on 2018-10-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0050_fts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('year', models.IntegerField()),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngrams', to='capdb.Jurisdiction', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='NgramWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10000, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ngram',
            name='w1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w1', to='capdb.NgramWord'),
        ),
        migrations.AddField(
            model_name='ngram',
            name='w2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w2', to='capdb.NgramWord'),
        ),
        migrations.AddField(
            model_name='ngram',
            name='w3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w3', to='capdb.NgramWord'),
        ),
        migrations.AddIndex(
            model_name='ngram',
            index=models.Index(fields=['w1', 'w2', 'w3'], name='capdb_ngram_w1_id_22799f_idx'),
        ),
    ]
