# Generated by Django 2.0.8 on 2018-10-03 20:41
# partial_index replaced 2019-04-02

from django.db import migrations
# import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0051_auto_20181001_1905'),
    ]

    operations = [
        # migrations.RemoveIndex is not idempotent, and we run it twice in dev,
        # when running `fab init_dev_db`
        migrations.RunSQL(
            sql='DROP INDEX IF EXISTS capdb_casem_court_i_42eeb9_partial;',
        ),
        # migrations.AddIndex(
        #     model_name='casemetadata',
        #     index=partial_index.PartialIndex(fields=['court_slug', 'decision_date', 'id'], name='capdb_casem_court_s_34d559_partial', unique=True, where='jurisdiction_id IS NOT NULL AND court_id IS NOT NULL AND NOT duplicative', where_postgresql='', where_sqlite=''),
        # ),
        migrations.RunSQL(
            sql="""CREATE UNIQUE INDEX capdb_casem_court_s_34d559_partial ON capdb_casemetadata USING btree (court_slug, decision_date, id) WHERE ((jurisdiction_id IS NOT NULL) AND (court_id IS NOT NULL) AND (NOT duplicative));""",
            reverse_sql='DROP INDEX capdb_casem_court_s_34d559_partial;',
        ),
    ]
