# Generated by Django 2.0.8 on 2018-11-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0056_casetext_tsv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumemetadata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='capdb.TrackingToolUser'),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='hollis_number',
            field=models.CharField(help_text='Identifier in the Harvard cataloging system, HOLLIS', max_length=9, null=True),
        ),
    ]
