# Generated by Django 2.0.13 on 2019-03-21 19:54

import capdb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0059_auto_20190305_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStyledXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styled_xml', capdb.models.XMLField()),
                ('mismatched', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='casexml',
            name='styled_xml',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xml', to='capdb.CaseStyledXML'),
        ),
        migrations.AddField(
            model_name='historicalcasexml',
            name='styled_xml',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.CaseStyledXML'),
        ),
    ]
