# Generated by Django 2.0.13 on 2019-03-14 19:46

import capdb.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0059_auto_20190305_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='casexml',
            name='styled_case_body',
            field=capdb.models.XMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasexml',
            name='styled_case_body',
            field=capdb.models.XMLField(blank=True, null=True),
        ),
    ]
