# Generated by Django 2.0.10 on 2019-04-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0060_auto_20190328_1742'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casefont',
            unique_together={('family', 'size', 'style', 'type', 'width')},
        ),
    ]
