# Generated by Django 2.0.10 on 2019-04-07 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0061_auto_20190404_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestructure',
            name='corrections',
        ),
    ]
