# Generated by Django 2.0.10 on 2019-04-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0062_remove_casestructure_corrections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citation',
            options={'ordering': ['type']},
        ),
        migrations.AddField(
            model_name='reporter',
            name='short_name_slug',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='volumes', to='capdb.Reporter'),
        ),
    ]
