# Generated by Django 2.0.10 on 2019-04-08 19:28

from django.db import migrations

def fill_reporter_slug(apps, schema_editor):
    Reporter = apps.get_model("capdb", "Reporter")
    for reporter in Reporter.objects.all():
        reporter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0063_auto_20190408_1928'),
    ]

    operations = [
        migrations.RunPython(fill_reporter_slug, migrations.RunPython.noop),
    ]
