# Generated by Django 2.2.1 on 2019-05-14 19:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0065_casemetadata_frontend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestructure',
            name='duplicates',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagestructure',
            name='extra_redacted_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
