# Generated by Django 2.2.1 on 2019-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0066_auto_20190514_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetadata',
            name='case_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='casexml',
            name='md5',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcasexml',
            name='md5',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalpagexml',
            name='md5',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalvolumexml',
            name='md5',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pagexml',
            name='md5',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='volumexml',
            name='md5',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
