# Generated by Django 2.2.2 on 2019-06-28 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0067_auto_20190529_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporter',
            name='is_nominative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporter',
            name='nominative_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nominative_reporters', to='capdb.Reporter'),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='nominative_reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nominative_volumes', to='capdb.Reporter'),
        ),
    ]
