# Generated by Django 2.2.2 on 2019-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0071_auto_20190717_1946'),
    ]

    operations = [
        # this file drops our existing partial indexes on CaseMetadata and replaces them with Django 2.2 partial indexes on CaseMetadata.in_scope

        # drop 0042_auto_20180614_1524
        migrations.RunSQL(
            sql='DROP INDEX capdb_casem_decisio_1d682b_partial;',
            reverse_sql="""CREATE UNIQUE INDEX capdb_casem_decisio_1d682b_partial ON capdb_casemetadata USING btree (decision_date, id) WHERE ((jurisdiction_id IS NOT NULL) AND (court_id IS NOT NULL) AND (NOT duplicative));""",
        ),
        migrations.RunSQL(
            sql='DROP INDEX capdb_casem_jurisdi_7edf20_partial;',
            reverse_sql="""CREATE UNIQUE INDEX capdb_casem_jurisdi_7edf20_partial ON capdb_casemetadata USING btree (jurisdiction_slug, decision_date, id) WHERE ((jurisdiction_id IS NOT NULL) AND (court_id IS NOT NULL) AND (NOT duplicative));""",
        ),
        # drop 0043_auto_20180614_1649
        migrations.RunSQL(
            sql='DROP INDEX capdb_casem_reporte_3f581c_partial;',
            reverse_sql="""CREATE UNIQUE INDEX capdb_casem_reporte_3f581c_partial ON capdb_casemetadata USING btree (reporter_id, decision_date, id) WHERE ((jurisdiction_id IS NOT NULL) AND (court_id IS NOT NULL) AND (NOT duplicative));""",
        ),
        # drop 0052_auto_20181003_2041
        migrations.RunSQL(
            sql='DROP INDEX capdb_casem_court_s_34d559_partial;',
            reverse_sql="""CREATE UNIQUE INDEX capdb_casem_court_s_34d559_partial ON capdb_casemetadata USING btree (court_slug, decision_date, id) WHERE ((jurisdiction_id IS NOT NULL) AND (court_id IS NOT NULL) AND (NOT duplicative));""",
        ),

        # create new indexes
        migrations.AddIndex(
            model_name='casemetadata',
            index=models.Index(condition=models.Q(in_scope=True), fields=['decision_date', 'id'], name='idx_in_scope'),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=models.Index(condition=models.Q(in_scope=True), fields=['reporter', 'decision_date', 'id'], name='idx_in_scope_reporter'),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=models.Index(condition=models.Q(in_scope=True), fields=['jurisdiction_slug', 'decision_date', 'id'], name='idx_in_scope_jurisdiction'),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=models.Index(condition=models.Q(in_scope=True), fields=['court_slug', 'decision_date', 'id'], name='idx_in_scope_court'),
        ),
    ]
