# Generated by Django 2.2.2 on 2019-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0073_auto_20190717_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvolumemetadata',
            name='duplicate',
            field=models.BooleanField(default=False, help_text='True if there is another volume with same cases'),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='duplicate',
            field=models.BooleanField(default=False, help_text='True if there is another volume with same cases'),
        ),
        migrations.AlterField(
            model_name='historicalvolumemetadata',
            name='legacy_duplicate',
            field=models.BooleanField(default=False, help_text='From tracking tool; we believe this indicates there is another volume with same hollis_number and volume_number'),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='legacy_duplicate',
            field=models.BooleanField(default=False, help_text='From tracking tool; we believe this indicates there is another volume with same hollis_number and volume_number'),
        ),
    ]
