# Generated by Django 2.2.4 on 2019-08-14 21:37

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0074_auto_20190717_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_index', models.IntegerField(null=True)),
                ('data', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caseimages', to='capdb.CaseMetadata')),
            ],
        ),
    ]
