# Generated by Django 2.2.4 on 2019-08-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0075_caseimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caseimage',
            unique_together={('case', 'hash')},
        ),
    ]
