# Generated by Django 2.2.4 on 2019-08-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0076_auto_20190827_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='no_index',
            field=models.BooleanField(default=False, help_text='True if case should not be included in google index'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='no_index_notes',
            field=models.TextField(blank=True, help_text='Reason no_index is true', null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced', to='capdb.CaseMetadata'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='withdrawn',
            field=models.BooleanField(default=False, help_text='True if case was withdrawn by the court'),
        ),
    ]
