# Generated by Django 2.2.4 on 2019-08-29 17:20

import capdb.versioning
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0077_auto_20190827_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='sys_period',
            field=capdb.versioning.DefaultDateTimeRangeField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricalCaseMetadata',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('case_id', models.CharField(db_index=True, max_length=64)),
                ('frontend_url', models.CharField(blank=True, max_length=255, null=True)),
                ('first_page', models.CharField(blank=True, max_length=255, null=True)),
                ('last_page', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_status', models.CharField(blank=True, max_length=255, null=True)),
                ('judges', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('parties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('opinions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('attorneys', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('docket_number', models.CharField(blank=True, max_length=20000)),
                ('docket_numbers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_date_original', models.CharField(blank=True, max_length=100)),
                ('argument_date_original', models.CharField(blank=True, max_length=100, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('district_abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.TextField(blank=True)),
                ('name_abbreviation', models.CharField(blank=True, db_index=True, max_length=1024)),
                ('date_added', models.DateTimeField(blank=True, editable=False, null=True)),
                ('duplicative', models.BooleanField(default=False, help_text='True if case was not processed because it is an unofficial case in a regional reporter')),
                ('duplicate', models.BooleanField(default=False, help_text='True if case was processed but is a duplicate of another preferred case')),
                ('withdrawn', models.BooleanField(default=False, help_text='True if case was withdrawn by the court')),
                ('no_index', models.BooleanField(default=False, help_text='True if case should not be included in google index')),
                ('no_index_notes', models.TextField(blank=True, help_text='Reason no_index is true', null=True)),
                ('in_scope', models.BooleanField(default=True, help_text='True if case should be included in public data')),
                ('initial_metadata_synced', models.BooleanField(default=False)),
                ('jurisdiction_name', models.CharField(blank=True, max_length=100, null=True)),
                ('jurisdiction_name_long', models.CharField(blank=True, max_length=100, null=True)),
                ('jurisdiction_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('jurisdiction_whitelisted', models.NullBooleanField()),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
                ('court_name_abbreviation', models.CharField(blank=True, max_length=100, null=True)),
                ('court_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('sys_period', capdb.versioning.DefaultDateTimeRangeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('court', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.Court')),
                ('duplicate_of', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.CaseMetadata')),
                ('jurisdiction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.Jurisdiction')),
                ('replaced_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.CaseMetadata')),
                ('reporter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.Reporter')),
                ('volume', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.VolumeMetadata')),
            ],
            options={
                'db_table': 'capdb_casemetadata_history',
                'ordering': ('-sys_period', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical case metadata',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
