# Generated by Django 2.2.4 on 2019-09-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0081_auto_20190919_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalreporter',
            old_name='end_year',
            new_name='analyst_end_year',
        ),
        migrations.RenameField(
            model_name='historicalreporter',
            old_name='start_year',
            new_name='analyst_start_year',
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='end_year',
            new_name='analyst_end_year',
        ),
        migrations.RenameField(
            model_name='reporter',
            old_name='start_year',
            new_name='analyst_start_year',
        ),
    ]
