# Generated by Django 2.2.4 on 2019-09-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0082_auto_20190919_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreporter',
            name='end_year',
            field=models.IntegerField(blank=True, help_text='Last year of cases for this reporter', null=True),
        ),
        migrations.AddField(
            model_name='historicalreporter',
            name='start_year',
            field=models.IntegerField(blank=True, help_text='First year of cases for this reporter', null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='end_year',
            field=models.IntegerField(blank=True, help_text='Last year of cases for this reporter', null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='start_year',
            field=models.IntegerField(blank=True, help_text='First year of cases for this reporter', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreporter',
            name='analyst_end_year',
            field=models.IntegerField(blank=True, help_text='Initial end year added by analyst.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalreporter',
            name='analyst_start_year',
            field=models.IntegerField(blank=True, help_text='Initial start year added by analyst.', null=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='analyst_end_year',
            field=models.IntegerField(blank=True, help_text='Initial end year added by analyst.', null=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='analyst_start_year',
            field=models.IntegerField(blank=True, help_text='Initial start year added by analyst.', null=True),
        ),
    ]
