# Generated by Django 2.2.7 on 2019-11-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0083_auto_20190919_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='robots_txt_until',
            field=models.DateTimeField(blank=True, help_text='Frontend URL for this case will be included in robots.txt until this date', null=True),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='robots_txt_until',
            field=models.DateTimeField(blank=True, help_text='Frontend URL for this case will be included in robots.txt until this date', null=True),
        ),
        migrations.AddIndex(
            model_name='casemetadata',
            index=models.Index(condition=models.Q(_negated=True, robots_txt_until=None), fields=['robots_txt_until'], name='idx_robots_txt_until'),
        ),
    ]
