# Generated by Django 2.2.7 on 2019-12-11 17:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0084_auto_20191119_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='custom_footer_message',
            field=models.TextField(blank=True, help_text='If not provided, custom footer will be filled with default text if elisions or redactions exist', null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='no_index_elided',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Text to be shown on click', null=True),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='no_index_redacted',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Text to be hidden from view', null=True),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='custom_footer_message',
            field=models.TextField(blank=True, help_text='If not provided, custom footer will be filled with default text if elisions or redactions exist', null=True),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='no_index_elided',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Text to be shown on click', null=True),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='no_index_redacted',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Text to be hidden from view', null=True),
        ),
    ]
