# Generated by Django 2.2.8 on 2019-12-16 18:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0085_auto_20191211_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetadata',
            name='no_index_elided',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Elided text will be shown on click. Example: {"Text to elide (must be exact match)": "Extra text that\'s currently not used. Can be left as empty string."}', null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='no_index_redacted',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Redacted text will be hidden from view and replaced with key\'s value specified above. Example: {"Text to redact (must be exact match)": "Text to replace redacted text."}', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='no_index_elided',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Elided text will be shown on click. Example: {"Text to elide (must be exact match)": "Extra text that\'s currently not used. Can be left as empty string."}', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='no_index_redacted',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Redacted text will be hidden from view and replaced with key\'s value specified above. Example: {"Text to redact (must be exact match)": "Text to replace redacted text."}', null=True),
        ),
    ]
