# Generated by Django 2.2.9 on 2020-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0087_auto_20191212_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='type',
            field=models.CharField(choices=[('official', 'official'), ('nominative', 'nominative'), ('parallel', 'parallel'), ('vendor', 'vendor')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='type',
            field=models.CharField(choices=[('official', 'official'), ('nominative', 'nominative'), ('parallel', 'parallel'), ('vendor', 'vendor')], max_length=100),
        ),
    ]
