# Generated by Django 2.2.9 on 2020-01-27 19:57

from django.db import migrations


def delete_denormalization_triggers(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    cursor.execute("DROP TRIGGER IF EXISTS denormalize_source ON capdb_jurisdiction")
    cursor.execute("DROP TRIGGER IF EXISTS denormalize_source ON capdb_court")
    cursor.execute("DROP TRIGGER IF EXISTS denormalize_dest ON capdb_casemetadata")
    cursor.execute("DROP TRIGGER IF EXISTS case_search_update_trigger ON capdb_casetext")


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0088_auto_20200116_1959'),
    ]

    operations = [
        migrations.RunPython(delete_denormalization_triggers, migrations.RunPython.noop),
    ]
