# Generated by Django 2.2.9 on 2020-01-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0089_auto_20200127_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetext',
            name='metadata',
        ),
        migrations.RemoveIndex(
            model_name='casemetadata',
            name='idx_in_scope',
        ),
        migrations.RemoveIndex(
            model_name='casemetadata',
            name='idx_in_scope_reporter',
        ),
        migrations.RemoveIndex(
            model_name='casemetadata',
            name='idx_in_scope_jurisdiction',
        ),
        migrations.RemoveIndex(
            model_name='casemetadata',
            name='idx_in_scope_court',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='court_name',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='court_name_abbreviation',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='court_slug',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='jurisdiction_name',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='jurisdiction_name_long',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='jurisdiction_slug',
        ),
        migrations.RemoveField(
            model_name='casemetadata',
            name='jurisdiction_whitelisted',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='court_name',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='court_name_abbreviation',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='court_slug',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='jurisdiction_name',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='jurisdiction_name_long',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='jurisdiction_slug',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='jurisdiction_whitelisted',
        ),
        migrations.DeleteModel(
            name='CaseText',
        ),
    ]
