# Generated by Django 2.2.10 on 2020-02-25 15:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0091_auto_20200210_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvolumemetadata',
            name='pdf_file',
            field=models.CharField(blank=True, default='', help_text='Exported volume PDF', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='pdf_file',
            field=models.FileField(blank=True, default='', help_text='Exported volume PDF', storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
