# Generated by Django 2.2.10 on 2020-02-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0091_auto_20200210_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_cite', models.CharField(db_index=True, max_length=10000)),
                ('reporter_original_string', models.CharField(max_length=200)),
                ('volume_original_number', models.CharField(blank=True, max_length=64, null=True)),
                ('page_original_number', models.SmallIntegerField()),
                ('case_origin', models.ManyToManyField(related_name='extractedcitations', to='capdb.CaseMetadata')),
                ('citation_match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='extractedcitations', to='capdb.Citation')),
                ('reporter_match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='extractedcitations', to='capdb.Reporter')),
                ('volume_match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='extractedcitations', to='capdb.VolumeMetadata')),
            ],
        ),
    ]
