# Generated by Django 2.2.10 on 2020-02-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0092_extractedcitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedcitation',
            name='page_original_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
