# Generated by Django 2.2.10 on 2020-02-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0093_auto_20200220_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedcitation',
            name='case_origin',
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='case_origins',
            field=models.ManyToManyField(related_name='extractedcitations', to='capdb.CaseMetadata'),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='citation_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extractedcitations', to='capdb.Citation'),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='original_cite',
            field=models.CharField(db_index=True, max_length=10000, unique=True),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='volume_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extractedcitations', to='capdb.VolumeMetadata'),
        ),
    ]
