# Generated by Django 2.2.10 on 2020-03-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0093_auto_20200226_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite_original', models.CharField(db_index=True, max_length=10000)),
                ('reporter_name_original', models.CharField(max_length=200)),
                ('volume_number_original', models.CharField(blank=True, max_length=64, null=True)),
                ('page_number_original', models.SmallIntegerField(blank=True, null=True)),
                ('cited_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='extractedcitations', to='capdb.CaseMetadata')),
            ],
        ),
    ]
