# Generated by Django 2.2.10 on 2020-03-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0093_auto_20200226_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_cite', models.CharField(db_index=True, max_length=10000, unique=True)),
                ('reporter_original_string', models.CharField(max_length=200)),
                ('volume_original_number', models.CharField(blank=True, max_length=64, null=True)),
                ('page_original_number', models.SmallIntegerField(blank=True, null=True)),
                ('case_origins', models.ManyToManyField(related_name='extractedcitations', to='capdb.CaseMetadata')),
            ],
        ),
    ]
