# Generated by Django 2.2.10 on 2020-02-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0094_auto_20200220_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedcitation',
            name='reporter_match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='extractedcitations', to='capdb.Reporter'),
        ),
    ]
