# Generated by Django 2.2.10 on 2020-03-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0094_extractedcitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedcitation',
            name='normalized_cite',
            field=models.SlugField(max_length=10000, null=True),
        ),
    ]
