# Generated by Django 2.2.10 on 2020-03-12 17:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0094_extractedcitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvolumemetadata',
            name='pdf_file',
            field=models.CharField(blank=True, help_text='Exported volume PDF', max_length=1000),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Exported volume PDF', max_length=1000, storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
