# Generated by Django 2.2.11 on 2020-03-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0095_auto_20200312_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedcitation',
            name='normalized_cite',
            field=models.SlugField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='cite_original',
            field=models.CharField(max_length=10000),
        ),
    ]
