# Generated by Django 2.2.11 on 2020-03-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0098_auto_20200325_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedcitation',
            name='page_number_original',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
