# Generated by Django 2.2.11 on 2020-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0099_auto_20200327_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedcitation',
            name='page_number_original',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
