# Generated by Django 2.2.11 on 2020-04-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0100_auto_20200410_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvolumemetadata',
            name='second_part_of',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='capdb.VolumeMetadata'),
        ),
        migrations.AddField(
            model_name='volumemetadata',
            name='second_part_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_part', to='capdb.VolumeMetadata'),
        ),
    ]
