# Generated by Django 2.2.13 on 2020-07-20 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0105_auto_20200717_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumemetadata',
            name='second_part_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_part', to='capdb.VolumeMetadata'),
        ),
    ]
