# Generated by Django 2.2.13 on 2020-07-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0106_auto_20200720_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='human_corrected',
            field=models.BooleanField(default=False, help_text="True if the case meets a 'human corrected' standard of accuracy"),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, help_text='User-visible date when the API response for this case last changed', null=True),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='human_corrected',
            field=models.BooleanField(default=False, help_text="True if the case meets a 'human corrected' standard of accuracy"),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='last_updated',
            field=models.DateTimeField(blank=True, editable=False, help_text='User-visible date when the API response for this case last changed', null=True),
        ),
        migrations.CreateModel(
            name='CorrectionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='correction_logs', to='capdb.CaseMetadata')),
            ],
        ),
    ]
