# Generated by Django 2.2.13 on 2020-07-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0108_auto_20200722_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemetadata',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='historicalcasemetadata',
            name='last_updated',
        ),
        migrations.CreateModel(
            name='CaseLastUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('indexed', models.BooleanField(db_index=True, default=False)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_update', to='capdb.CaseMetadata')),
            ],
        ),
    ]
