# Generated by Django 2.2.13 on 2020-09-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0110_caseanalysis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casemetadata',
            options={'permissions': [('correct_ocr', 'Can use OCR editor')]},
        ),
    ]
