# Generated by Django 2.2.19 on 2021-04-01 16:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0111_auto_20200910_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='rdb_cite',
            field=models.CharField(help_text='Citation in standard reporters-db format', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='rdb_normalized_cite',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='rdb_cite',
            field=models.CharField(help_text='Citation in standard reporters-db format', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='rdb_normalized_cite',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='target_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cited_by', to='capdb.CaseMetadata'),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='target_cases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='If cite is ambiguous, list of possible IDs.', null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='rdb_cite',
            field=models.CharField(help_text='Citation in standard reporters-db format', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='rdb_normalized_cite',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='cited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='extracted_citations', to='capdb.CaseMetadata'),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='normalized_cite',
            field=models.CharField(db_index=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalreporter',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalreporter',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
