# Generated by Django 2.2.20 on 2021-04-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0112_auto_20210401_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='cite',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='citation',
            name='normalized_cite',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='cite',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='normalized_cite',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['cite'], name='capdb_citat_cite_14ab80_idx'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['normalized_cite'], name='capdb_citat_normali_eedcab_idx'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['rdb_cite'], name='capdb_citat_rdb_cit_430bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='citation',
            index=models.Index(fields=['rdb_normalized_cite'], name='capdb_citat_rdb_nor_cb632c_idx'),
        ),
    ]
