# Generated by Django 3.2 on 2021-04-20 21:05

import capdb.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0113_auto_20210414_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseanalysis',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='casebodycache',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseinitialmetadata',
            name='metadata',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='attorneys',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='docket_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='judges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='no_index_elided',
            field=models.JSONField(blank=True, help_text='Elided text will be shown on click. Example: {"Text to elide (must be exact match)": "Extra text that\'s currently not used. Can be left as empty string."}', null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='no_index_redacted',
            field=models.JSONField(blank=True, help_text='Redacted text will be hidden from view and replaced with key\'s value specified above. Example: {"Text to redact (must be exact match)": "Text to replace redacted text."}', null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='opinions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='parties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casestructure',
            name='opinions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datamigration',
            name='alto_xml_changed',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datamigration',
            name='alto_xml_rollback',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datamigration',
            name='case_xml_changed',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datamigration',
            name='case_xml_rollback',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datamigration',
            name='volume_xml_changed',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='datamigration',
            name='volume_xml_rollback',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='attorneys',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='docket_numbers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='judges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='no_index_elided',
            field=models.JSONField(blank=True, help_text='Elided text will be shown on click. Example: {"Text to elide (must be exact match)": "Extra text that\'s currently not used. Can be left as empty string."}', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='no_index_redacted',
            field=models.JSONField(blank=True, help_text='Redacted text will be hidden from view and replaced with key\'s value specified above. Example: {"Text to redact (must be exact match)": "Text to replace redacted text."}', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='opinions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='parties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpagestructure',
            name='blocks',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='historicalpagestructure',
            name='duplicates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpagestructure',
            name='extra_redacted_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpagestructure',
            name='font_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpagestructure',
            name='spaces',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvolumemetadata',
            name='bibliographic_review',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Complete', 'Complete'), ('Yes', 'Yes')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvolumemetadata',
            name='ingest_errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvolumemetadata',
            name='task_statuses',
            field=models.JSONField(default=dict, help_text='Date and results of tasks run for this volume'),
        ),
        migrations.AlterField(
            model_name='historicalvolumemetadata',
            name='xml_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagestructure',
            name='blocks',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pagestructure',
            name='duplicates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagestructure',
            name='extra_redacted_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagestructure',
            name='font_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagestructure',
            name='spaces',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='bibliographic_review',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Complete', 'Complete'), ('Yes', 'Yes')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='ingest_errors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Exported volume PDF', max_length=1000, storage=capdb.storages.DownloadOverlayStorage(base_url='http://case.test:8000/download/', location='/Users/jcushman/Documents/capstone/capstone/test_data/downloads'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='task_statuses',
            field=models.JSONField(default=dict, help_text='Date and results of tasks run for this volume'),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='xml_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
