# Generated by Django 3.2.3 on 2021-05-27 20:40

import capdb.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0114_auto_20210420_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedcitation',
            name='page_number_original',
        ),
        migrations.RemoveField(
            model_name='extractedcitation',
            name='reporter_name_original',
        ),
        migrations.RemoveField(
            model_name='extractedcitation',
            name='volume_number_original',
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='category',
            field=models.CharField(blank=True, help_text="Source and cite_type from reporters-db, e.g. 'laws:leg_statute'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='groups',
            field=models.JSONField(blank=True, help_text='Dict of groups from eyecite cite.', null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Dict of metadata from eyecite cite.', null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='pin_cites',
            field=models.JSONField(blank=True, help_text='List of pin cites and parentheticals from this cite cluster.', null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='reporter',
            field=models.CharField(help_text='Standardized reporter string from reporters-db', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='weight',
            field=models.SmallIntegerField(default=1, help_text='Number of citations in cited_by, counting short cites.'),
        ),
        migrations.AddField(
            model_name='extractedcitation',
            name='year',
            field=models.SmallIntegerField(help_text='Year included in citation.', null=True),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='normalized_cite',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Exported volume PDF', max_length=1000, storage=capdb.storages.DownloadOverlayStorage(base_url='http://case.test:8000/download/', location='/app/test_data/downloads'), upload_to=''),
        ),
    ]
