# Generated by Django 3.2.4 on 2021-06-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0115_auto_20210527_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
