# Generated by Django 3.2.5 on 2021-07-29 01:24

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0116_auto_20210728_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedcitation',
            name='opinion_id',
            field=models.SmallIntegerField(blank=True, help_text='Index of opinion making this citation', null=True),
        ),
    ]


