# Generated by Django 3.2.6 on 2021-08-16 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0117_extractedcitation_opinion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='batch',
            field=models.CharField(default='2018', max_length=255),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='source',
            field=models.CharField(choices=[('CAP', 'CAP'), ('Fastcase', 'Fastcase')], default='CAP', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='batch',
            field=models.CharField(default='2018', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='source',
            field=models.CharField(choices=[('CAP', 'CAP'), ('Fastcase', 'Fastcase')], default='CAP', max_length=10),
        ),
        migrations.AlterField(
            model_name='extractedcitation',
            name='opinion_id',
            field=models.SmallIntegerField(blank=True, help_text='Id of opinion making extracted citation.', null=True),
        ),
        migrations.CreateModel(
            name='FastcaseImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('path', models.CharField(max_length=1000)),
                ('batch', models.CharField(max_length=1000)),
                ('case', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fastcase_import', to='capdb.casemetadata')),
                ('duplicate_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fastcase_duplicates', to='capdb.casemetadata')),
            ],
        ),
    ]
