# Generated by Django 3.2.6 on 2021-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0118_auto_20210816_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('indexed', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
