# Generated by Django 3.2.7 on 2021-09-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0119_casedeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemetadata',
            name='source',
            field=models.CharField(choices=[('Harvard', 'Harvard'), ('Fastcase', 'Fastcase')], default='Harvard', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcasemetadata',
            name='source',
            field=models.CharField(choices=[('Harvard', 'Harvard'), ('Fastcase', 'Fastcase')], default='Harvard', max_length=10),
        ),
    ]
