# Generated by Django 3.2.23 on 2023-12-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capdb', '0120_auto_20210916_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='static_file_name',
            field=models.CharField(blank=True, help_text='Name of static file to export case to', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasemetadata',
            name='static_file_name',
            field=models.CharField(blank=True, help_text='Name of static file to export case to', max_length=255, null=True),
        ),
    ]
