# Generated by Django 2.2.3 on 2019-07-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
                ('page_link', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
