# Generated by Django 2.2.3 on 2019-07-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        )
    ]
