# Generated by Django 2.2.11 on 2020-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capweb', '0002_galleryentry_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryentry',
            name='title_slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerysection',
            name='title_slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
