# Generated by Django 2.2.13 on 2020-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capweb', '0003_auto_20200331_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerysection',
            name='description',
            field=models.TextField(blank=True, help_text='markdown-formatted text'),
        ),
        migrations.AlterField(
            model_name='galleryentry',
            name='content',
            field=models.TextField(help_text='markdown-formatted text'),
        ),
    ]
