# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('caseid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('firstpage', models.IntegerField()),
                ('lastpage', models.IntegerField()),
                ('jurisdiction', models.CharField(max_length=100)),
                ('citation', models.CharField(max_length=255)),
                ('docketnumber', models.CharField(max_length=255)),
                ('decisiondate', models.DateField()),
                ('decisiondate_original', models.CharField(max_length=100)),
                ('court', models.TextField()),
                ('name', models.TextField()),
                ('court_abbreviation', models.CharField(max_length=255)),
                ('name_abbreviation', models.CharField(max_length=255)),
                ('volume', models.CharField(max_length=45)),
            ],
        ),
    ]
