# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True
    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('caseid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('firstpage', models.IntegerField(blank=True, null=True)),
                ('lastpage', models.IntegerField(blank=True, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('citation', models.CharField(blank=True, max_length=255)),
                ('docketnumber', models.CharField(blank=True, max_length=255)),
                ('decisiondate', models.DateField(blank=True, null=True)),
                ('decisiondate_original', models.CharField(blank=True, max_length=100)),
                ('court', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('court_abbreviation', models.CharField(blank=True, max_length=255)),
                ('name_abbreviation', models.CharField(blank=True, max_length=255)),
                ('volume', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, error_messages={b'unique': 'A user with that email address already exists.'}, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_validated', models.BooleanField(default=False)),
                ('case_allowance', models.IntegerField(default=500)),
                ('is_researcher', models.BooleanField(default=False)),
                ('activation_nonce', models.CharField(blank=True, max_length=40, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('key_expires', models.DateTimeField(blank=True, null=True)),
            ],

            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='caseuser',
            options={'verbose_name': 'User'},
        ),
    ]
