# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='citation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_abbreviation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='decisiondate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='decisiondate_original',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='docketnumber',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='firstpage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='lastpage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name_abbreviation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='volume',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
