# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0001_initial_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reporter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
