# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0002_case_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
