# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0002_auto_20161015_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='decisiondate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='firstpage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='lastpage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
