# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0003_case_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=45)),
                ('value', models.TextField(blank=True, null=True)),
                ('caseid', models.CharField(max_length=255)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
