# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0004_caseerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
