# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0005_auto_20161111_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caseuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
