# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0007_auto_20161115_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseuser',
            name='case_allowance_last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
