# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0008_caseuser_case_allowance_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseuser',
            name='is_validated',
        ),
    ]
