# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0009_remove_caseuser_is_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name',models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('jurisdiction', models.SlugField(null=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='case',
            name='reporter_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capi_project.Reporter'),
        ),

    ]
