# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db import IntegrityError
from django.db import transaction
from django.template.defaultfilters import slugify

def create_reporters(apps, schema_editor):
    Reporter = apps.get_model("capi_project", "Reporter")
    Case = apps.get_model("capi_project", "Case")
    for case in Case.objects.all():
        try:
            special_cases =  {
                    'Ct. Cl.':  {
                        'West Virginia':'wv-ct-cl', 'United States': 'us-ct-cl'},
                    'Smith': {
                        'Indiana':'ind-smith', 'New Hampshire':'nh-smith'
                    }
                }
            if case.reporter in special_cases:
                slug = special_cases[case.reporter][case.jurisdiction]
            else:
                slug = slugify(case.reporter)

            reporter, created = Reporter.objects.get_or_create(name=case.reporter, slug=slug, jurisdiction=slugify(case.jurisdiction))

            if not created:
                reporter.save()
            case.reporter_name = reporter
            case.save()

        except IntegrityError as e:
            print "ERROR", reporter, case.jurisdiction, case.reporter
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0010_auto_20161214_1621'),
    ]

    operations = [
        migrations.RunPython(create_reporters)
    ]
