# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0011_reporter_foreignkey'),
    ]

    operations = [
        migrations.RemoveField('case', 'reporter'),
        migrations.RenameField('case', 'reporter_name', 'reporter'),
    ]
