# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0012_auto_20161216_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_abbreviation', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capi_project.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='case',
            name='court_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capi_project.Court'),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='capi_project.Jurisdiction'),
        ),
    ]
