# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0013_auto_20161216_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(unique=True)),
                ('year', models.IntegerField(blank=True)),
                ('number', models.IntegerField(blank=True)),
                ('date_added', models.DateTimeField()),
                ('publisher', models.CharField(max_length=255)),
                ('publisher_place', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='jurisdiction',
            name='name_abbreviation',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='end_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='name_abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reporter',
            name='volumes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='reporter',
            name='jurisdiction_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='capi_project.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capi_project.Reporter'),
        ),
    ]
