# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0014_auto_20170104_1858'),
    ]

    def jurisdiction_forwards_func(apps, schema_editor):
        Case = apps.get_model('capi_project','Case')
        Jurisdiction = apps.get_model('capi_project','Jurisdiction')
        for case in Case.objects.all():

            common_errors = {
                'Califonia':'California',
                'United Statess': 'United States',
                'N.Y.': 'New York',
                '1': 'United States',
                'Philadelphia':'Pennsylvania',
            }

            jurisdiction_name = case.jurisdiction

            if common_errors.get(case.jurisdiction):
                jurisdiction_name = common_errors[case.jurisdiction]
            try:
                jurisdiction, created = Jurisdiction.objects.get_or_create(name=case.jurisdiction)
            except:
                print 'errored on %s %s' % (case.caseid, case.jurisdiction)

            case.jurisdiction = jurisdiction.name
            case.jurisdiction_name = jurisdiction
            case.save()
        print 'done writing jurisdictions'

    def jurisdiction_backwards_func(apps, schema_editor):
        Case = apps.get_model('capi_project','Case')
        for case in Case.objects.all():
            jur_name = case.jurisdiction_name.name
            case.jurisdiction = jur_name
            case.save()

    operations = [
        migrations.RunPython(jurisdiction_forwards_func, jurisdiction_backwards_func),
    ]
