# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0015_auto_20170104_2003'),
    ]

    operations = [
        migrations.RemoveField('case', 'jurisdiction'),
        migrations.RenameField('case', 'jurisdiction_name', 'jurisdiction'),

        migrations.RemoveField(
            model_name='volume',
            name='publisher_place',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='year',
        ),
        migrations.AddField(
            model_name='volume',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='nominative_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='volume',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='capi_project.Reporter'),
        ),
    ]
