# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('capi_project', '0016_auto_20170104_2311'),
    ]

    def jurisdiction_forwards_func(apps, schema_editor):
        Reporter = apps.get_model('capi_project', 'Reporter')
        Jurisdiction = apps.get_model('capi_project', 'Jurisdiction')
        # in reporter, jurisdiction is a slug
        # deslugify: replace '-' with spaces
        #   match jurisdiction.name__iexact because of lower cased strings
        for rep in Reporter.objects.all():
            jur_slug = rep.jurisdiction
            jur = jur_slug.replace('-', ' ')
            jur_obj = Jurisdiction.objects.filter(name__iexact=jur).first()
            rep.jurisdiction_name = jur_obj
            rep.save()

    operations = [
        migrations.AlterField(
            model_name='case',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='capi_project.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='jurisdiction_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='capi_project.Jurisdiction'),
        ),
        migrations.RunPython(jurisdiction_forwards_func)
    ]
