# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0019_case_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='court_abbreviation',
        ),
        migrations.RemoveField('case', 'court'),
        migrations.RenameField('case', 'court_name', 'court'),
    ]
