# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capi_project', '0020_auto_20170105_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_court', to='capi_project.Court'),
        ),
        migrations.AlterField(
            model_name='case',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_jurisdiction', to='capi_project.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_reporter', to='capi_project.Reporter'),
        ),
        migrations.AlterField(
            model_name='court',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_jurisdiction', to='capi_project.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_jurisdiction', to='capi_project.Jurisdiction'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume_reporter', to='capi_project.Reporter'),
        ),
    ]
