# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='case_allowance',
            new_name='case_allowance_remaining',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='total_case_allowance',
            field=models.IntegerField(blank=True, default=500, null=True),
        ),
    ]
