# Generated by Django 2.0.2 on 2018-04-03 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0002_auto_20171211_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='capapi.APIUser'),
        ),
    ]
