# Generated by Django 2.0.2 on 2018-04-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0002_auto_20180420_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capuser',
            name='is_researcher',
        ),
        migrations.AddField(
            model_name='capuser',
            name='unlimited_access_until',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
