# Generated by Django 2.0.2 on 2018-07-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0003_auto_20180426_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='capuser',
            name='normalized_email',
            field=models.CharField(default='temp@example.com', help_text='Used to ensure that new emails are unique.', max_length=255),
            preserve_default=False,
        ),
    ]
