# Generated by Django 2.0.8 on 2018-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0006_sitelimits'),
    ]

    operations = [
        migrations.AddField(
            model_name='capuser',
            name='agreed_to_tos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='capuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
