# Generated by Django 2.0.8 on 2018-11-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0008_researchrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitelimits',
            options={'verbose_name_plural': 'Site limits'},
        ),
        migrations.AddField(
            model_name='capuser',
            name='unlimited_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='researchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied'), ('awaiting signature', 'awaiting signature')], default='pending', max_length=20, verbose_name='research request status'),
        ),
    ]
