# Generated by Django 2.0.8 on 2018-11-01 16:02

from django.db import migrations
from django.utils import timezone


def set_unlimited_access_boolean(apps, schema_editor):
    CapUser = apps.get_model("capapi", "CapUser")
    CapUser.objects.filter(unlimited_access_until__gt=timezone.now()).update(unlimited_access=True)

class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0009_auto_20181101_1601'),
    ]

    operations = [
        migrations.RunPython(set_unlimited_access_boolean, migrations.RunPython.noop)
    ]
