# Generated by Django 2.0.8 on 2018-11-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0011_auto_20181105_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvardContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_signature_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('area_of_interest', models.TextField(blank=True, null=True)),
                ('contract_html', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-user_signature_date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_signature_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('area_of_interest', models.TextField(blank=True, null=True)),
                ('contract_html', models.TextField(blank=True, null=True)),
                ('approver_signature_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied')], default='pending', max_length=20, verbose_name='research contract status')),
                ('approver_notes', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-user_signature_date'],
            },
        ),
        migrations.AddField(
            model_name='capuser',
            name='harvard_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researchcontract',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvardcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvard_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
