# Generated by Django 2.0.8 on 2018-11-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0012_auto_20181107_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrequest',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
