# Generated by Django 2.0.13 on 2019-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0013_auto_20181107_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': "You're already subscribed."}, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('do_not_email', models.BooleanField(default=False)),
            ],
        ),
    ]
