# Generated by Django 2.2.4 on 2019-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0014_mailinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='capuser',
            name='deactivated_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capuser',
            name='deactivated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
