# Generated by Django 2.2.8 on 2019-12-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0015_auto_20190812_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='capuser',
            name='mailing_list',
            field=models.BooleanField(default=False),
        ),
    ]
