# Generated by Django 2.2.9 on 2020-01-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0016_capuser_mailing_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='capuser',
            name='has_tracked_history',
            field=models.BooleanField(default=False, help_text='Whether this user has history entries'),
        ),
        migrations.AddField(
            model_name='capuser',
            name='track_history',
            field=models.BooleanField(default=False, help_text='Whether to record cases accessed by this user'),
        ),
    ]
