# Generated by Django 2.2.10 on 2020-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0017_auto_20200121_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBlocklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, help_text="Exact match for email domain, e.g. 'example.com'", max_length=1000)),
                ('regex', models.CharField(blank=True, help_text="Postgres regex match for entire email address, e.g. '\\yfoo@.*\\.com\\y'", max_length=1000)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
