# Generated by Django 2.2.11 on 2020-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0018_emailblocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcontract',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied'), ('withdrawn', 'withdrawn')], default='pending', max_length=20, verbose_name='research contract status'),
        ),
        migrations.AlterField(
            model_name='researchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied'), ('awaiting signature', 'awaiting signature'), ('withdrawn', 'withdrawn')], default='pending', max_length=20, verbose_name='research request status'),
        ),
    ]
