# Generated by Django 3.2.11 on 2022-01-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0019_auto_20200324_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchcontract',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchcontract',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
