# Generated by Django 2.2.16 on 2021-02-17 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labs', '0002_auto_20210217_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temp_rename',
            new_name='Timeline',
        ),
    ]
