# Generated by Django 2.2.19 on 2021-03-30 18:20

from django.db import migrations, models
from labs.models import get_short_uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20210217_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='uuid',
            field=models.CharField(default=get_short_uuid, max_length=10, null=True),
        ),
    ]
