# Generated by Django 2.2.19 on 2021-04-01 12:46

from django.db import migrations
from labs.models import get_short_uuid


def gen_uuid(apps, schema_editor):
    TimelineModel = apps.get_model('labs', 'timeline')
    for row in TimelineModel.objects.all():
        row.uuid = get_short_uuid()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_timeline_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
