# Generated by Django 2.2.19 on 2021-04-02 15:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_timeline_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
