# Generated by Django 3.2 on 2021-04-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_timeline_ids_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='timeline',
            field=models.JSONField(default=dict),
        ),
    ]
