version: '2.2'
services:
  db:
    build:
      context: ../services/docker
      dockerfile: extended-postgres.dockerfile
      cache_from:
        - type: registry
        - ref: "registry.lil.tools/harvardlil/cap-db:buildcache"
      cache_to:
        - type: registry
        - ref: "registry.lil.tools/harvardlil/cap-db:buildcache,type=max"
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-db:0.8-bc582483e3741366137113cb651ba221
        platforms:
          - linux/amd64
      x-hash-paths:
        - extended-postgres.dockerfile
  web:
    build:
      context: .
      cache_from:
        - type: registry
        - ref: "registry.lil.tools/harvardlil/cap-web:buildcache"
      cache_to:
        - type: registry
        - ref: "registry.lil.tools/harvardlil/cap-web:buildcache,type=max"
      x-bake:
        tags:
          - registry.lil.tools/harvardlil/cap-web:194-676f1f8b50689e7bada6324a4afff03f
        platforms:
          - linux/amd64
      x-hash-paths:
        - requirements.txt
        - yarn.lock
