# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 21:54


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, error_messages={b'unique': 'A user with that email address already exists.'}, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('case_allowance', models.IntegerField(default=500)),
                ('case_allowance_last_updated', models.DateTimeField(auto_now_add=True)),
                ('is_researcher', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('activation_nonce', models.CharField(blank=True, max_length=40, null=True)),
                ('key_expires', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('caseid', models.CharField(max_length=255, unique=True)),
                ('firstpage', models.IntegerField(blank=True, null=True)),
                ('lastpage', models.IntegerField(blank=True, null=True)),
                ('citation', models.CharField(blank=True, max_length=255)),
                ('docketnumber', models.CharField(blank=True, max_length=255)),
                ('decisiondate', models.DateField(blank=True, null=True)),
                ('decisiondate_original', models.CharField(blank=True, max_length=100)),
                ('name', models.TextField(blank=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=255)),
                ('volume', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=45)),
                ('value', models.TextField(blank=True, null=True)),
                ('caseid', models.CharField(max_length=255)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_abbreviation', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField()),
                ('name_abbreviation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.IntegerField(blank=True, null=True)),
                ('end_date', models.IntegerField(blank=True, null=True)),
                ('volumes', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('slug', models.SlugField(null=True)),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporter_jurisdiction', to='capapi.Jurisdiction')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('nominative_number', models.IntegerField(blank=True, default=None, null=True)),
                ('date_added', models.DateTimeField(null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_year', models.IntegerField(blank=True, default=None, null=True)),
                ('start_year', models.IntegerField(blank=True, default=None, null=True)),
                ('end_year', models.IntegerField(blank=True, default=None, null=True)),
                ('pages', models.IntegerField(blank=True, default=None, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volume_reporter', to='capapi.Reporter')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_jurisdiction', to='capapi.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_court', to='capapi.Court'),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_jurisdiction', to='capapi.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_reporter', to='capapi.Reporter'),
        ),
    ]
