# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 22:37


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volume',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
