# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capapi', '0002_auto_20170412_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseuser',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True),
        ),
    ]
