# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0003_auto_20170705_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMetadata',
            fields=[
                ('barcode', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('first_page', models.IntegerField(blank=True, null=True)),
                ('last_page', models.IntegerField(blank=True, null=True)),
                ('citation', models.CharField(blank=True, max_length=255)),
                ('docket_number', models.CharField(blank=True, max_length=255)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_date_original', models.CharField(blank=True, max_length=100)),
                ('name', models.TextField(blank=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_abbreviation', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name_abbreviation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='volumemetadata',
            name='hollis_number',
            field=models.CharField(help_text='Identifier in the Harvard cataloging system, HOLLIS', max_length=9),
        ),
        migrations.AddField(
            model_name='court',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_jurisdiction', to='cap.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_court', to='cap.Court'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='jurisdiction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_jurisdiction', to='cap.Jurisdiction'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casemetadata_reporter', to='cap.Reporter'),
        ),
        migrations.AddField(
            model_name='casemetadata',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap.VolumeMetadata'),
        ),
    ]
